# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "resend-rs"
version = "0.4.0"
edition = "2021"
license = "GPL-3.0"
readme = "./README.md"

authors = ["Antonios Barotsis <antonios.barotsis@pm.me>"]
repository = "https://github.com/AntoniosBarotsis/resend-rs"
homepage = "https://github.com/AntoniosBarotsis/resend-rs"
documentation = "https://docs.rs/resend-rs"

categories = ["email", "web-programming"]
keywords = ["email", "resend"]
description = "A minimal Resend client."

[features]
default = ["native-tls"]

blocking = ["reqwest/blocking", "maybe-async/is_sync"]
native-tls = ["reqwest/native-tls"]
rustls-tls = ["reqwest/rustls-tls"]

[dependencies]
reqwest = { version = "0.12.3", default-features = false, features = ["json"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = { version = "1.0.115" }
thiserror = { version = "1.0.58" }
maybe-async = { version = "0.2.10" }
ecow = { version = "0.2.2", features = ["serde"] }

[dev-dependencies]
tokio = { version = "1.37.0", features = ["macros", "test-util", "rt-multi-thread"] }
