[package]
name = "resend-rs"
description = "A very minimal Resend client for sending emails."
version = "0.2.0"
edition = "2021"
repository = "https://github.com/AntoniosBarotsis/resend-rs"
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
async = []

[dependencies]
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls", "blocking"] }
thiserror = "1.0.43"
